post_install() {
  dkms install -m rtbth/${1%-*}
  systemctl enable rtbth.service
  systemctl start rtbth.service
}

pre_upgrade() {
  systemctl stop rtbth.service
  dkms remove -m rtbth/${1%-*} --all ${2}
}

post_upgrade() {
  dkms install -m rtbth/${1%-*} ${1}
  systemctl start rtbth.service
}

pre_remove() {
  systemctl stop rtbth.service
  systemctl disable rtbth.service
  dkms remove -m rtbth/${1%-*} --all
}

post_remove() {
  systemctl daemon-reload
}
